# Generated by Django 4.1.5 on 2023-01-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='static/img/laptopbrand/')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPUBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='static/img/cpubrand/')),
                ('teamcolor', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPUBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='static/img/gpubrand/')),
                ('teamcolor', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='1920 x 1080', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SSD 500 GB', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='static/img/laptop/')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='8 GB', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.FloatField(default='15.6', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='static/img/usage/')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(default=10000)),
                ('readyforsell', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cpu')),
                ('cpubrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cpubrand')),
                ('disp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.laptopdisplay')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.laptopdrive')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.gpu')),
                ('gpubrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.gpubrand')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.laptopimage')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.laptopram')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.laptopsize')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.usage')),
            ],
        ),
    ]
