# Generated by Django 4.1.5 on 2023-01-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_recommendlaptop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendLaptop',
        ),
    ]
